version: "3"
services:
  icecast:
    image: moul/icecast
    volumes:
      - ./logs:/var/log/icecast2
    environment:
      - ICECAST_SOURCE_PASSWORD=temp
      - ICECAST_ADMIN_PASSWORD=temp
      - ICECAST_PASSWORD=trainjam
      - ICECAST_RELAY_PASSWORD=trainjam
    ports:
      - "8000:8000"
  virtualdj:
    build: ./virtualdj
    volumes:
      - ./virtualdj:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    links:
      - mongo_db
  mongo_db:
    image: "mongo"
    volumes:
      - ./mongo_data:/data/db
    expose:
      - 27017
